import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { FileText, Shield, Crosshair, AlertTriangle, ArrowRight, Download, CheckCircle2 } from 'lucide-react'
import { useWargameStore, TurnResult } from '../store/wargameStore'

export default function ReportsPage() {
  const navigate = useNavigate()
  const { activeSessionId, turnHistory, currentTurnResult } = useWargameStore()
  const [selectedTurn, setSelectedTurn] = useState<TurnResult | null>(currentTurnResult || (turnHistory.length > 0 ? turnHistory[turnHistory.length - 1] : null))

  const activeReportTurn = selectedTurn || currentTurnResult || (turnHistory.length > 0 ? turnHistory[turnHistory.length - 1] : null)

  return (
    <div className="max-w-[1500px] mx-auto px-6 py-6 space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-slate-800 pb-6">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono tracking-widest text-emerald-400 uppercase">
            <FileText className="w-4 h-4" />
            <span>STRATEGIC DECISION REPORTS ARCHIVE</span>
          </div>
          <h1 className="text-3xl font-display font-bold text-white tracking-wide mt-1">
            STRATEGIC REPORTS & MEMORY ARCHIVE
          </h1>
          <p className="text-sm text-slate-400 mt-1 max-w-2xl">
            Synthesized AI evaluation reports, risk dossiers, trade-off matrices, and operational recommendations produced during campaign execution.
          </p>
        </div>
      </div>

      {!activeSessionId || turnHistory.length === 0 ? (
        <div className="bg-[rgba(4,15,26,0.85)] border border-slate-800 rounded-xl p-12 text-center font-mono space-y-4">
          <FileText className="w-12 h-12 text-slate-600 mx-auto animate-pulse" />
          <h3 className="text-lg font-bold text-white">No Reports Available</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto">
            Strategic reports are automatically generated by the Report Agent at the end of each wargaming turn.
          </p>
          <button
            onClick={() => navigate('/wargaming')}
            className="px-5 py-2.5 rounded bg-[#42C7FF] text-space-navy font-display font-bold text-xs uppercase tracking-wider hover:bg-[#63E6FF] transition-all inline-flex items-center gap-2"
          >
            <span>LAUNCH WARGAME SESSION</span>
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Left Column: Turn Selector Sidebar */}
          <div className="space-y-4">
            <div className="font-mono text-xs font-bold text-slate-400 uppercase tracking-wider">
              CAMPAIGN REPORTS ({turnHistory.length})
            </div>

            <div className="space-y-2">
              {turnHistory.map((t) => {
                const isSelected = activeReportTurn?.turn_number === t.turn_number
                return (
                  <button
                    key={t.turn_number}
                    onClick={() => setSelectedTurn(t)}
                    className={`w-full text-left p-4 rounded-xl font-mono text-xs border transition-all space-y-1 ${
                      isSelected
                        ? 'bg-[#42C7FF]/15 border-[#42C7FF] text-white shadow-[0_0_15px_rgba(66,199,255,0.2)]'
                        : 'bg-[rgba(4,15,26,0.8)] border-slate-800 text-slate-400 hover:border-slate-700 hover:text-white'
                    }`}
                  >
                    <div className="flex items-center justify-between font-bold">
                      <span>TURN {t.turn_number} REPORT</span>
                      <span className="text-[10px] text-cyan-400">{t.session_status}</span>
                    </div>
                    <div className="text-[11px] truncate text-slate-300">
                      COA: {t.decisions.blue_coa_name}
                    </div>
                  </button>
                )
              })}
            </div>
          </div>

          {/* Right Column: Full Strategic Report Viewer */}
          <div className="lg:col-span-3 space-y-6">
            {activeReportTurn && (
              <div className="bg-[rgba(4,15,26,0.85)] border border-[rgba(100,190,255,0.2)] rounded-xl p-6 backdrop-blur-md space-y-6">
                <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                  <div>
                    <span className="text-xs font-mono text-emerald-400 font-bold uppercase">
                      STRATEGIC DECISION REPORT // TURN {activeReportTurn.turn_number}
                    </span>
                    <h2 className="text-xl font-display font-bold text-white mt-1">
                      {activeReportTurn.decisions.blue_coa_name}
                    </h2>
                  </div>
                  <div className="font-mono text-xs text-slate-400">
                    Session: {activeReportTurn.session_id}
                  </div>
                </div>

                {/* Strategic Evaluation Sections */}
                <div className="space-y-6">
                  <div>
                    <h3 className="text-xs font-mono text-slate-400 uppercase font-bold mb-2">Executive Strategic Conclusion</h3>
                    <p className="bg-[#02070D]/80 border border-slate-800 p-4 rounded-lg font-mono text-xs text-slate-200 leading-relaxed">
                      {activeReportTurn.evaluation.strategic_conclusion}
                    </p>
                  </div>

                  {/* Operational Implications */}
                  {activeReportTurn.evaluation.strategic_implications && activeReportTurn.evaluation.strategic_implications.length > 0 && (
                    <div>
                      <h3 className="text-xs font-mono text-cyan-400 uppercase font-bold mb-2">Strategic & Operational Implications</h3>
                      <ul className="bg-cyan-950/20 border border-cyan-500/20 p-4 rounded-lg font-mono text-xs text-slate-200 list-disc list-inside space-y-1.5">
                        {activeReportTurn.evaluation.strategic_implications.map((imp, i) => (
                          <li key={i}>{imp}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {/* Markdown Strategic Dossier Text */}
                  {activeReportTurn.strategic_report && (
                    <div>
                      <h3 className="text-xs font-mono text-emerald-400 uppercase font-bold mb-2">Synthesized Decision Dossier</h3>
                      <div className="bg-[#02070D]/90 border border-slate-800 p-5 rounded-lg font-mono text-xs text-slate-300 leading-relaxed whitespace-pre-wrap font-sans">
                        {activeReportTurn.strategic_report}
                      </div>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
