"""
Orchestrator Agent.
The central reasoning authority responsible for constructing the Dynamic Scenario Contract.
Does NOT directly execute simulations. Passes contracts to deterministic validation.
"""

from typing import Optional, Dict, Any
from rich import print

from backend.schemas.contracts import (
    ScenarioContract,
    ScenarioMetadata,
    ScenarioObjectives,
    ScenarioConstraints,
    ScenarioActors,
    ScenarioGeography,
    ScenarioEnvironment,
    ScenarioRules,
    InformationState,
    HumanInputData,
    ExternalInformation,
    ResolvedAgentContext,
    ScenarioTransition,
)
from backend.llm.wrapper import invoke_structured, is_fallback_allowed


class OrchestratorAgent:
    def __init__(self):
        self.role = "orchestrator"

    def _deterministic_fallback(
        self,
        scenario_id: str,
        parent_scenario_id: Optional[str],
        human_guidance: Optional[str]
    ) -> ScenarioContract:
        """Deterministic resilient fallback scenario contract."""
        return ScenarioContract(
            scenario_id=scenario_id,
            parent_scenario_id=parent_scenario_id,
            metadata=ScenarioMetadata(
                title=f"Operation Resolve Phase {scenario_id}",
                description="Continuation of strategic standoff in disputed valley corridor (Fallback Generation)",
                time_horizon="48h",
                classification="FALLBACK"
            ),
            objectives=ScenarioObjectives(
                primary=["Secure Forward Logistics Point Alpha", "Deter river crossing"],
                secondary=["Protect civilian bridge infrastructure"],
                success_conditions=["Zero friendly territory ceded", "Logistics point operational"],
                failure_conditions=["Enemy establishes bridgehead south of river"]
            ),
            constraints=ScenarioConstraints(
                hard=[{"id": "HC-001", "description": "Remain within Eastern Valley boundary", "enforcement": "BLOCK"}],
                operational=["Maintain supply convoy route"],
                political=["No kinetic cross-border strikes"]
            ),
            actors=ScenarioActors(
                blue={"role": "Coalition Defense Vanguard", "doctrine": "Active Defense"},
                red={"role": "Opposing Force", "doctrine": "Encirclement"}
            ),
            forces={
                "blue": [{"id": "BLUE-BDE-1", "name": "1st Mech Brigade", "type": "Mechanized Infantry", "strength": 94, "location": "LOC-ALPHA"}],
                "red": [{"id": "RED-DIV-1", "name": "4th Armored Column", "type": "Armored Column", "strength": 108, "location": "LOC-BRAVO"}],
                "third_party": []
            },
            resources={
                "blue": {"fuel": 80, "ammo": 85},
                "red": {"fuel": 115, "ammo": 90},
                "shared": {"bridge_capacity": 50}
            },
            geography=ScenarioGeography(
                area_of_operations={"name": "Eastern Valley", "bounds": [34.0, 74.0, 34.5, 74.5]},
                key_locations=[
                    {"id": "LOC-ALPHA", "name": "Forward Logistics Point Alpha"},
                    {"id": "LOC-BRAVO", "name": "River Crossing Point"}
                ],
                terrain={"type": "Valley Basin", "traversability": "Moderate"}
            ),
            environment=ScenarioEnvironment(
                weather={"condition": "Rain", "status": "Degrading"},
                visibility={"range_km": 6.5},
                terrain_conditions={"ground": "Muddy trails"}
            ),
            rules=ScenarioRules(
                rules_of_engagement=["Defensive fires only"],
                engagement_rules=["Visual identification required"],
                movement_rules=["Mud reduces wheeled speed by 35%"]
            ),
            information_state=InformationState(
                known_facts=["Adversary halted at north river bank"],
                uncertainties=["Arrival time of Red logistics echelon"]
            ),
            human_input=HumanInputData(
                strategic_guidance=[human_guidance or "Consolidate defensive perimeter"]
            ),
            external_information=ExternalInformation(
                sources=["UN Observer SitRep #14"],
                relevant_events=["Temporary lull in cross-border artillery"]
            ),
            dynamic={"transition_note": "Generated by deterministic fallback generator"}
        )

    def generate_scenario_contract(
        self,
        scenario_id: str,
        parent_scenario_id: Optional[str],
        context: ResolvedAgentContext,
        transition: Optional[ScenarioTransition] = None,
        human_guidance: Optional[str] = None
    ) -> ScenarioContract:
        """
        Synthesizes historical memory, human guidance, constraints, and transition requirements
        to generate a valid Dynamic Scenario Contract.
        """
        system_prompt = (
            "You are the ORCHESTRATOR AGENT of the NIRNAY Strategic Wargaming & Decision Intelligence Platform.\n"
            "Your sole responsibility is to construct a rigorous, coherent Dynamic Scenario Contract.\n"
            "CORE ARCHITECTURAL INVARIANTS:\n"
            "1. Agents reason. Deterministic systems execute. Persistent memory remembers. Humans remain in control.\n"
            "2. The Orchestrator generates scenarios based on objective, constraints, memory, and evaluation transitions.\n"
            "3. Hard constraints are absolute and non-negotiable.\n"
            "4. Output MUST adhere strictly to the ScenarioContract schema."
        )

        user_prompt = (
            f"Generate Scenario Contract for scenario_id='{scenario_id}' (parent_scenario_id='{parent_scenario_id or 'None'}').\n\n"
            f"CRITICAL: The output JSON MUST include the top-level property \"scenario_id\": \"{scenario_id}\".\n"
            f"Resolved Context:\n{context.context}\n\n"
            f"Human Guidance: {human_guidance or 'Maintain active defensive posture and test adversarial intent.'}\n"
        )
        if transition:
            user_prompt += (
                f"\nTransition Directives from previous evaluation:\n"
                f"- Reason: {transition.reason}\n"
                f"- Required Changes: {transition.required_changes}\n"
                f"- Emergent Developments: {transition.emergent_events}\n"
            )

        try:
            return invoke_structured(
                role=self.role,
                system_prompt=system_prompt,
                user_prompt=user_prompt,
                schema=ScenarioContract,
                temperature=0.3
            )
        except Exception as e:
            if not is_fallback_allowed():
                raise e
            print(f"[bold yellow][AGENT WARNING][/bold yellow] Orchestrator LLM failed: {e}. Using deterministic fallback.")
            return self._deterministic_fallback(scenario_id, parent_scenario_id, human_guidance)
